import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import SessionWrapper from "@/lib/SessionWrapper";
import { Toaster } from "@/components/ui/toaster";
import { RouteGuard } from "@/components/auth-guard/auth-guard";
import Navbar from "@/components/layout/headers";
import Head from "next/head";

// import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Head>
          <link
            href="https://fonts.googleapis.com/css2?family=Chewy&display=swap"
            rel="stylesheet"
          />
        </Head>
        <SessionWrapper>
          <Toaster />
          {/* <Header /> */}
          <Navbar />
          {/* <RouteGuard> */}
          <div className="md:px-8 px-3 ">{children}</div>
          {/* </RouteGuard> */}
        </SessionWrapper>
      </body>
    </html>
  );
}
